<?php

namespace AppBundle\Repository;

/**
 * CommandGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
